extension SpriteSheet {
    static let claude8Bit = SpriteSheet(
        idle: [idleBreatheRelaxed, idleBreatheSquashed],
        walk: [walkContactFrontFoot, walkPassingRise, walkContactBackFoot, walkPassingRiseAlternate],
        wave: [waveArmLowered, waveArmMidway, waveArmRaised],
        sit: [sitEyesOpen, sitEyesClosed],
        emerge: [emergeSquintUnderDirt, emergeEyesOpenWide, emergeShakeOffDirt],
        dive: [diveGlanceDownward, diveSquashedFlat, diveDustPuffSettling]
    )

    private static let idleBreatheRelaxed = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let idleBreatheSquashed = PixelFrame([
        "................",
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        ".#oooooooaaOOO#.",
        "..#ooooooOOOO#..",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let walkContactFrontFoot = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "...ooO...ooO....",
        ".........####...",
    ])

    private static let walkPassingRise = PixelFrame([
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        "AA#AAAAAAAAAA#..",
        ".a#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        ".....oo.ooO.....",
        "....###.####....",
        "................",
    ])

    private static let walkContactBackFoot = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "AA.#ooooooOO#...",
        ".a#AAAAAAAAAA#..",
        "..#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "...ooO...ooO....",
        "...###..........",
    ])

    private static let walkPassingRiseAlternate = PixelFrame([
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "..#aaaaaaaaaa#..",
        "Aa#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "......oo.ooO....",
        ".....###.####...",
        "................",
    ])

    private static let waveArmLowered = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#o.",
        "..#oooooooaaO#o.",
        "..#ooooooooOO#O.",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let waveArmMidway = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#o.",
        "...#ooooooOO#.o.",
        ".A#AAAAAAAAAA#O.",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let waveArmRaised = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#w.",
        "..#ooooeeoeeO#o.",
        "..#oooooooooO#O.",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let sitEyesOpen = PixelFrame([
        "................",
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        ".#oooooooaaOOO#.",
        ".#ooooooooooOO#.",
        ".#OooooooooOOO#.",
        "..###ooo##ooo##.",
    ])

    private static let sitEyesClosed = PixelFrame([
        "................",
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#wooooooooo#..",
        "..#oooo##o##O#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        ".#oooooooaaOOO#.",
        ".#ooooooooooOO#.",
        ".#OooooooooOOO#.",
        "..###ooo##ooo##.",
    ])

    private static let emergeSquintUnderDirt = PixelFrame([
        ".........O......",
        "...#O#O.#.O#O...",
        ".....######.....",
        "...#wwoooooo#...",
        "..#wooo##o##o#..",
        "..#oooooooooO#..",
        "..#oooooooooO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let emergeEyesOpenWide = PixelFrame([
        "...O.........#..",
        "....#....O......",
        ".....######.....",
        "...#wwoooooo#...",
        "..#woooeeoeeo#..",
        "..#ooooeeoeeO#..",
        "..#ooooeeoeeO#..",
        "..#oooooo##oO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let emergeShakeOffDirt = PixelFrame([
        "................",
        "....#.......O...",
        "......######....",
        "....#wwoooooo#..",
        ".O.#woooeeoeeo#.",
        "O..#ooooeeoeeO#.",
        ".O.#oooooooooO#.",
        "...#oooooo##oO#.",
        "....#ooooooOO#..",
        "..A#AAAAAAAAAA#.",
        ".Aa#aaaaaaaaaa#.",
        "...#oooooooaaO#.",
        "...#ooooooooOO#.",
        "....#ooooOOOO#..",
        ".....ooO..ooO...",
        ".....###..####..",
    ])

    private static let diveGlanceDownward = PixelFrame([
        "................",
        "................",
        ".....######.....",
        "...#wwoooooo#...",
        "..#wooooooooo#..",
        "..#oooooooooO#..",
        "..#ooooeeoeeO#..",
        "..#ooooeeoeeO#..",
        "...#ooooooOO#...",
        ".A#AAAAAAAAAA#..",
        "Aa#aaaaaaaaaa#..",
        "..#oooooooaaO#..",
        "..#ooooooooOO#..",
        "...#ooooOOOO#...",
        "....ooO..ooO....",
        "....###..####...",
    ])

    private static let diveSquashedFlat = PixelFrame([
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "....########....",
        "..#wwoooooooo#..",
        ".#woooo##o##oO#.",
        "A#AAAAAAAAAAAA#.",
        "a#aaaaaaaaaaaa#.",
        ".#oooooooooOOO#.",
        "..############..",
    ])

    private static let diveDustPuffSettling = PixelFrame([
        "................",
        "................",
        "................",
        "......O..#......",
        "...#........O...",
        "...#O......O#...",
        "..#OO#....#OO#..",
        ".#OOO#....#OOO#.",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ])
}
